FROM node as prod
WORKDIR /app
COPY package.json .
COPY yarn.lock .
RUN yarn install --frozen-lock
COPY . .
RUN yarn build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=prod /app/build /usr/share/nginx/html
